### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by jepunband** [keraattin/EmailAnalyzer#23]
hello, i got some trace back error when analyzing the header from outlook.

Traceback (most recent call last):
  File "/home/dexter/tools/email-header-analyzer/mha/server.py", line 65, in dateParser
    r = dateutil.parser.parse(line, fuzzy=True)
  File "/home/dexter/.local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dexter/.local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: from JH0PR02MB6921.apcprd02.prod.outlook.com (2603:1096:990:53::14)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dexter/.local/lib/python3.10/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/dexter/.local/lib/python3.10/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
  File "/home/dexter/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dexter/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dexter/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dexter/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/dexter/tools/email-header-analyzer/mha/server.py", line 115, in index
    org_time = dateParser(line[-1])
  File "/home/dexter/tools/email-header-analyzer/mha/server.py", line 72, in dateParser
    r = dateutil.parser.parse(r[0])
  File "/home/dexter/.local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dexter/.local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)

**Comment by keraattin** [comment]
Hello, can you give me more details about bug with using **Bug Report Template**

```
**Bug Description**
A clear and concise description of what the bug is.

**Expected Behavior or Results**
A clear and concise description of what you expected to happen.

**Reproduce Steps**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Desktop (please complete the following information):**
 - OS with Version : [e.g. iOS]
 - Python Version : [e.g Python 3.10]
 - Browser with Version : [e.g. chrome, safari] (If Applicable)
 - EmailAnalyzer Project Version : [e.g. v2.0]

**Screenshots or Attachments (If Applicable)**
If applicable, add screenshots or attachments to help explain your problem.

**Additional context**
Add any other context about the problem here.
```
